name: Automated Testing

on:
    push:

permissions:
    contents: read

jobs:
    composer:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.4'
                      lock-version: '3.4'
                    - php-version: '7.4'
                      lock-version: '4.4'
                    - php-version: '8.0'
                      lock-version: '5.0'
                    - php-version: '8.1'
                      lock-version: '6.0'
                    - php-version: '8.2'
                      lock-version: '7.0'

        steps:
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - uses: actions/checkout@v4

            - name: Set versions
              run: cp composer.${{ matrix.lock-version }}.lock composer.lock

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

    phpunit:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.4'
                      lock-version: '3.4'
                    - php-version: '7.4'
                      lock-version: '4.4'
                    - php-version: '8.0'
                      lock-version: '5.0'
                    - php-version: '8.1'
                      lock-version: '6.0'
                    - php-version: '8.2'
                      lock-version: '7.0'

        steps:
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - uses: actions/checkout@v4

            - name: Set versions
              run: cp composer.${{ matrix.lock-version }}.lock composer.lock

            - name: Install dependencies
              uses: ramsey/composer-install@v3

            - name: Run test suite
              run: composer run-script phpunit

    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "7.4"

            - uses: actions/checkout@v4

            - name: Install dependencies
              uses: ramsey/composer-install@v3

            - name: PHPStan analyse
              run: composer run-script phpstan-analise
