name: PHP Composer

on:
    push:

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                include:
                    - php-version: '7.4'
                    - php-version: '8.0'
                    - php-version: '8.1'

        steps:
            - uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
            # Docs: https://getcomposer.org/doc/articles/scripts.md

            - name: Run test suite
              run: composer run-script test

            - name: PHPStan analyse
              run: vendor/bin/phpstan analyse
