name: PHP Composer

on:
    push:

permissions:
    contents: read

jobs:
    phpunit:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.1'
                      symfony-version: '3.4.*'
                      phpunit-version: '7.5.20'
                    - php-version: '7.4'
                      symfony-version: '4.0.*'
                      phpunit-version: '9.5.28'
                    - php-version: '8.0'
                      symfony-version: '5.0.*'
                      phpunit-version: '9.5.28'
                    - php-version: '8.1'
                      symfony-version: '6.0.*'
                      phpunit-version: '9.5.28'
                    - php-version: '8.1'
                      symfony-version: '^6.2'
                      phpunit-version: '9.5.28'

        steps:
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Set versions
              run: composer run-script set_versions ${{ matrix.symfony-version }} ${{ matrix.phpunit-version }}

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: Run test suite
              run: composer run-script phpunit

    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "7.4"

            - uses: actions/checkout@v3

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: PHPStan analyse
              run: composer run-script phpstan-analise
